In [11]:
import numpy as np

arr=np.array([1, 2, 3, 4, 5, 4, 4])

x4=np.where(arr==4)
print(x4)

for i in x4:
    print(arr[i])


(array([3, 5, 6], dtype=int64),)
[4 4 4]


In [13]:
arr=np.array([1,0,3,2])
print(np.sort(arr))

[0 1 2 3]


In [15]:
ascending=np.sort(arr)
dAscending=ascending[::-1]
print(dAscending)

[3 2 1 0]


In [16]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr))

['apple' 'banana' 'cherry']


In [17]:
arr=np.array([[3,7,4],[8,0,1]])
print(np.sort(arr))

[[3 4 7]
 [0 1 8]]


In [21]:
arr=np.array([[3,7,4],[8,0,1]])
arr.shape

(2, 3)

In [29]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new=arr.reshape(6,2)
print(new)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [30]:
arr=np.array([[3,7,4],[8,0,1]])
new=arr.reshape(-1)
print(new)

[3 7 4 8 0 1]
