In [2]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
a=np.array(45)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [6]:
arr=np.array([1,2,3,4])
print(arr[1]+arr[3])

6


In [11]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,2])

9


In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,0,2])

9


In [14]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[-1,-2])

11


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr[2:8])

[3 4 5 6 7 8]


In [16]:
print(arr[5:])

[ 6  7  8  9 10 11 12]


In [17]:
print(arr[:6])

[1 2 3 4 5 6]


In [18]:
print(arr[-6:-2])

[ 7  8  9 10]


In [19]:
print(arr[1:8:2])

[2 4 6 8]


In [20]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr[1,2:5])

[ 9 10 11]


In [23]:
print(arr[0:2,1:6])

[[ 2  3  4  5  6]
 [ 8  9 10 11 12]]


In [24]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
arr=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

for i in arr:
    print(i)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [26]:
for i in arr:
    for x in i:
        print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [27]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
