In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

type(arr)

[1 2 3 4 5]


numpy.ndarray

In [3]:
a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [4]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [7]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [10]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [11]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[-1, -2])

9


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [13]:
print(arr[4:])

[5 6 7]


In [14]:
print(arr[:4])

[1 2 3 4]


In [15]:
print(arr[-3:-1])

[5 6]


In [16]:
print(arr[1:5:2])

[2 4]


In [17]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [19]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [20]:
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [22]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [23]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
